export const Users = [
  {
    id: 1,
    profilePicture: "./assets/person/1.jpg",
    username: "Ali Ajibade",
  },
  {
    id: 1,
    profilePicture: "./assets/person/1.jpeg",
    username: "Alex Brown",
  },
  {
    id: 1,
    profilePicture: "./assets/person/1.jpeg",
    username: "Bode Badmus",
  },
  {
    id: 2,
    profilePicture: "./assets/person/2.jpeg",
    username: "Jide Kosoko",
  },
  {
    id: 3,
    profilePicture: "./assets/person/3.jpeg",
    username: "Tunji Afolabi",
  },
  {
    id: 4,
    profilePicture: "./assets/person/4.jpeg",
    username: "Dele Osabiya",
  },
  {
    id: 5,
    profilePicture: "./assets/person/5.jpeg",
    username: "Abiodun Adebayo",
  },
  {
    id: 6,
    profilePicture: "./assets/person/6.jpeg",
    username: "Jimi Agbaje",
  },
  {
    id: 7,
    profilePicture: "./assets/person/7.jpeg",
    username: "Tunde Ajibade",
  },
  {
    id: 8,
    profilePicture: "./assets/person/8.jpeg",
    username: "Olayemi Alao",
  },
  {
    id: 9,
    profilePicture: "./assets/person/9.jpeg",
    username: "Lola Ibiyemi",
  },
  {
    id: 10,
    profilePicture: "./assets/person/10.jpeg",
    username: "Harry Porter",
  },
];


export const Posts = [
  {
    id: 1,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/2.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/3.jpeg",
    date: "5 mins ago",
    userId: 3,
    like: 32,
    comment: 9,
  },
  {
    id: 4,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/4.jpeg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/5.jpeg",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 9,
  },
  {
    id: 6,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/6.jpeg",
    date: "5 mins ago",
    userId: 6,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/7.jpeg",
    date: "5 mins ago",
    userId: 7,
    like: 32,
    comment: 9,
  },
  {
    id: 8,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/8.jpeg",
    date: "5 mins ago",
    userId: 8,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/9.jpeg",
    date: "5 mins ago",
    userId: 9,
    like: 32,
    comment: 9,
  },
  {
    id: 10,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/10.jpeg",
    date: "5 mins ago",
    userId: 10,
    like: 32,
    comment: 9,
  },
];
