export const Users = [
  {
    id: 1,
    profilePicture: "./assets/person/1.jpg",
    username: "Muhammar Gadaffi",
  },
  {
    id: 2,
    profilePicture: "./assets/person/2.jpeg",
    username: "Bright Smith",
  },
  {
    id: 3,
    profilePicture: "./assets/person/3.jpg",
    username: "Henry Stone",
  },
  {
    id: 4,
    profilePicture: "./assets/person/4.jpeg",
    username: "Mary Osabiya",
  },
  {
    id: 5,
    profilePicture: "./assets/person/5.jpg",
    username: "Frank Odey",
  },
  {
    id: 6,
    profilePicture: "./assets/person/6.jpeg",
    username: "Bola Agbaje",
  },
  {
    id: 7,
    profilePicture: "./assets/person/7.jpeg",
    username: "Tunde Ajibade",
  },
  {
    id: 8,
    profilePicture: "./assets/person/8.jpg",
    username: "Steve Jobs",
  },
  {
    id: 9,
    profilePicture: "./assets/person/9.jpg",
    username: "Lola Ibiyemi",
  },
  {
    id: 10,
    profilePicture: "./assets/person/10.png",
    username: "Harry Porter",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/2.jpeg",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/3.jpeg",
    date: "5 mins ago",
    userId: 3,
    like: 32,
    comment: 9,
  },
  {
    id: 4,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/4.jpeg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/5.jpeg",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 9,
  },
  {
    id: 6,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/6.jpeg",
    date: "5 mins ago",
    userId: 6,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/7.jpeg",
    date: "5 mins ago",
    userId: 7,
    like: 32,
    comment: 9,
  },
  {
    id: 8,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/8.jpeg",
    date: "5 mins ago",
    userId: 8,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/9.jpeg",
    date: "5 mins ago",
    userId: 9,
    like: 32,
    comment: 9,
  },
  {
    id: 10,
    desc: "Love for all, hatred for none.",
    photo: "./assets/post/10.jpeg",
    date: "5 mins ago",
    userId: 10,
    like: 32,
    comment: 9,
  },
];
